### ISSUE TITLE
Authoring/Hosting project tooling support 

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#663]
Creating an issue to track the status of end-to-end C# Authoring/Hosting. Here is a list of hacks that we should remove to consider authoring/hosting experience complete:
- [x] Instead of winmd reference from hosting project, allow for project reference to the component - Joshua
- [x] Remove need for `DeploymentContent` set to true in hosting project file (for the manifest and runtimeconfig) - Joshua
- [ ] Automate activatable classes instead of manually creating manifest file - Mano (#789)
- [x] Remove need for creating WinRT.Host.runtimeconfig.json (create a default, and allow override) - Joshua (#735)
- [x] `CsWinRTEnableLogging` in authoring csproj (#687) - Mano
- [x] `CsWinRTWindowsMetadata` (#657) 
- [x] `GeneratedFilesDir` in authoring csproj bug with potential race condition - Mano
- [x] `AssemblyVersion` - can we set a default
- [x] Copy hosting dlls so you don't need Directory.build.targets files (#474)

For packaged apps, there are some additional hacks:
- [x] Manually copying CsWinRT and component assemblies to the Appx folder on deploy (#734)
- [x] Manually editing the appxmanifest (may need VS help), for example:
```xml
<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>WinRT.Host.dll</Path>
          <ActivatableClass ActivatableClassId="Net5BgTaskComponent.BgTask" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
```

Other existing issues for E2E authoring support include:
- [x] #633 
- [x] #656 
- [ ] #649 
- [x] #662

**Comment by j0shuams** [comment]
Hosting support needs some more work with ProjectReferences, but PackageRef's are handled by my PR #665

**Comment by j0shuams** [comment]
Meeting notes:

Top priority is project reference support, as a few of the later hacks we want to see if they are needed once projref support is in place. 

Second priority: manifest/runtimeconfig

- Mano will work on embedding manifest in authored component, with the hope that consumers wont need to make a manifest file at all.

- Joshua will work on making a generic runtimeconfig, and shipping it with DeploymentContent metadata -- consumers wont need to author one unless they want to make a custom one (by referring to the hosting docs)

**Comment by angelazhangmsft** [comment]
Closing and tracking the remaining items separately
